default: &default
  endpoint: "https://acme-v01.api.letsencrypt.org/"
  email: "yuhaidongyhd@gmail.com"
  domain: "teeceepee.com nerv.teeceepee.com"

  # in Rails.root, path to private key
  private_key: "letsencrypt/key_file.pem"

  # Private key stored in the database
  # private_key_in_db: true

  # in Rails.root, path where certificates will be stored
  # NOTE: on Heroku, this variable is ignored
  output_cert_dir: "letsencrypt/"

  # in Rails.root, path where challenge token will be stored
  # in situations when database will not be used
  # NOTE: on Heroku, comment out this line and use the database
  challenge_dir_name: "letsencrypt/"
  cert_name: "teeceepee.com"

production:
  # if 'cert_name' is set, the keys are saved with this name, if not the first string from key 'domain' will be used
  <<: *default

development:
  # if 'cert_name' is set, the keys are saved with this name, if not the first string from key 'domain' will be used
  <<: *default
