defaults: &defaults
  foo:
    bar: baz
  asset_host:
  mailer:
    default_from:
    default_to:
  oss:
    endpoint:
    access_key_id:
    access_key_secret:
  oss_dir:
  smtp_settings:
    user_name:
    password:

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
