defaults: &defaults
  foo:
    bar: baz
  smtp_settings:
    user_name:
    password:
  mailer:
    default_from:
    default_to:

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
